theme: jekyll-theme-cayman

exclude: ["README.md"]

title: Victors dynamiske hjemmeside
description: null
author:
  name: Victor Keinicke Todd-Moir
  email: v.toddmoir@gmail.com
  github: Todden96

production_url: https://todden96.github.io/
